### ISSUE TITLE
Stages not working

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#128]
I have 
```
export let options =  {
    vusMax: 100,
    duration: "10m",
    stages:
        [{target: 10, duration: "20s"},
         {target: 15, duration: "20s"},
         {target: 20, duration: "20s"},
         {target: 20, duration: "40s"},
         {target: 0, duration: "10s"}],    
    maxRedirects: 15,
    insecureSkipTLSVerify: true,
}

```
I would expect to go from 0-10 vu the first 20 seconds, 10 to 15 the next 20 seconds and so on.

**Except I get nothing. k6 starts and remains at "starting"**

**k6 inspect shows this**
```
duration: 10m
insecureSkipTLSVerify: true
iterations: null
linger: null
maxRedirects: 15
noUsageReport: null
paused: null
stages:
- duration: 20000000000
 target: 10
- duration: 20000000000
 target: 15
- duration: 20000000000
 target: 20
- duration: 40000000000
 target: 20
- duration: 10000000000
 target: 0
thresholds: null
vus: null
vusMax: 100

```
I assume duration times are in Go default units, nano seconds.
