### ISSUE TITLE
k6 github action testing on local server

### ISSUE THREAD

**Issue by m-restieri** [loadimpact/k6#1536]
I am trying to create a github action which uses k6 to test on a localhost server, but the server refuses to connect.
## Environment

- k6 version: 0.26.2
- OS and version: Mac OS 10.14.6
- Docker version and image, if applicable:

## Expected Behavior

Create a github action which performs load testing on each push on a local instance (port 3000).

## Actual Behavior

In the github action when trying to run the tests, all the requests refuse to connect to the server, despite working when locally tested.

## Steps to Reproduce the Problem

The test script is a very basic typescript file that just calls http.get on a localhost url with some thresholds for performance. Here is the .yml file that I have been using for the github action:
```
name: k6 Load Tests
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: DEPLOYMENT=dev npm run build
            - run: |
                npm start & \
                    npx wait-on http://127.0.0.1:3000
            - name: Run k6 tests
              uses: k6io/action@v0.1
              with:
                filename: __tests__/k6-loadTest.ts
```
Error message which appears at all of the requests:
`time="2020-07-06T20:12:08Z" level=warning msg="Request Failed" error="Get http://127.0.0.1:3000/ci-test: dial tcp 127.0.0.1:3000: connect: connection refused"`

**Comment by simskij** [comment]
Hi, and thank you for the report! 🙏🏼

Is `3000` the port on which your application is exposed when you run `npm start`?

If not, please change the port to the one your application is exposed on.
If it is, could you please paste the surrounding logs as well?

Thanks,
Simme

**Comment by m-restieri** [comment]
Hi Simme,

Yes, 3000 is the correct port, but I'm not sure if the action could be messing with/changing the port?

Here is a screenshot of the surrounding logs (same message for all requests).
<img width="1062" alt="Screen Shot 2020-07-07 at 10 58 45 AM" src="https://user-images.githubusercontent.com/61026215/86800269-d9a30180-c040-11ea-8c8a-a211ee5b0f2b.png">

**Comment by simskij** [comment]
Could you please check the logs for the previous step as well? 😅

**Comment by m-restieri** [comment]
Yes, here is a screenshot.
<img width="1088" alt="Screen Shot 2020-07-07 at 2 53 51 PM" src="https://user-images.githubusercontent.com/61026215/86828843-bccaf600-c061-11ea-8c11-076af1c0ffe0.png">

**Comment by simskij** [comment]
It seems like something has changed in how actions work, as I can't get it to work anymore either.
With that said, running against a local server is still possible, just not with the marketplace action:

```yaml

name: Main Workflow
on: [push]
  jobs:
    build:
      name: Run k6 test
      runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k6
        run: |
           curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Start server and run tests
        run: |
          npm start & npx wait-on http://localhost:3000
          ./k6 run test.js
```

**Comment by m-restieri** [comment]
I am now getting a syntax error for the workflow that you provided, even tho it appears to be valid yaml syntax.
<img width="1041" alt="Screen Shot 2020-07-09 at 11 39 49 AM" src="https://user-images.githubusercontent.com/61026215/87060902-0db12a80-c1d9-11ea-835b-9aeed7b4568a.png">

**Comment by simskij** [comment]
> I am now getting a syntax error for the workflow that you provided, even tho it appears to be valid yaml syntax.
> <img alt="Screen Shot 2020-07-09 at 11 39 49 AM" width="1041" src="https://user-images.githubusercontent.com/61026215/87060902-0db12a80-c1d9-11ea-835b-9aeed7b4568a.png">

My bad, the indentation is off:

```
name: Main Workflow
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Start server and run tests
        run: |
          npm start & npx wait-on http://localhost:3000
          ./k6 run test.js
```

**Comment by m-restieri** [comment]
Got it, it works now. Thanks! Here is the final workflow file for reference, had to add build.
```
name: k6 Load Tests
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Build
        run: |
          DEPLOYMENT=dev npm run build
      - name: Start server and run tests
        run: |
          npm start & npx wait-on http://localhost:3000
          ./k6 run __tests__/k6-loadTest.ts
```

**Comment by starRMS** [comment]
Hai I wanna ask something,

Here is my workflow:

```yaml
# This workflow will run an end-to-end test with k6 scripts.

name: k6_end_to_end_test

on:
  pull_request:
    branches: ["testing"]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Spin up container to run e2e
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Run k6 e2e test
        run: ./k6 run testing/end_to_end_test.js

      - name: Remove container
        run: docker-compose -f docker-compose.test.yml down
```

The docker basically consist of my backend server. Docker step is already running well. When it comes to k6, turns out it outputs like:
```
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

time="2024-01-30T08:44:43Z" level=error msg="The moduleSpecifier \"testing/end_to_end_test.js\" couldn't be retrieved from the resolved url \"https://testing/end_to_end_test.js\". Error : \"Get https://testing/end_to_end_test.js: dial tcp: lookup testing on 12[7](https://github.com/SC-Starcapital/sun-rec/actions/runs/7708459356/job/21007580014?pr=38#step:5:8).0.0.53:53: server misbehaving\""
```

Instead of running the script located on `testing/end_to_end_test.js`, it hits `https://testing/end_to_end_test.js:`. I have no idea what's going on.

Please help anyone @m-restieri @simskij
